
// if you're using pannel carefully edit this part.

const sessionName = 'session';
const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYUp2c1dLRW1zTVhUdzA2aUJtYkNMd3RUQVZNVHdkelljWENTbmQxOWdIRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQzg2QWx1Mi9ocm9mRlJEb2Jza0h1amFKcmFjM25LZjJoNHhGN3RHZjhnRT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI4R0h6NkFtNW9xWlFpVDYwVkdSeDl6bmdCcUh4MGFrL1RBMlZlZldqUkY0PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJzb1dWNmRiRzNKcUVFUExUYkthaklWVWFmaGNkN1pqbEsyVHhHWTNucndBPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImdOVUdvV2hzZ3FkVVFpZkRkckFhRk40MlpDcllHcDFLZ2ZrMWhITWhBMTg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlpsOXV5UFV6dHZ6SmpoSGRLMU5vbHRuV282MElVdnkyMDVyL3ZuaTV4SFE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVUF5MDY3VUFsd1pKWit6MkVxWnI5ckE5L0FXUTl2bktFV0lXOUtMekcxYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUENaTHRFdjV5azJuaDJ1ZU0wZUFqeUhVd3FuNVpodEl6N3h0REdtN2wyND0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InFpODdld0lnYStjalFzcGJFL2pqQXo5WVE1R053WjlWTzZUclBpMXhaRlJ2L00wUWIrU0xmaWc5eWZPY2IreXUyN0QvQ0FZdzVRTlA1K1FiMWVjRWh3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjksImFkdlNlY3JldEtleSI6IlFKTnFXV21KU1BiRmpmbGIzd2hGaU5KWVhoVzVIU1drOWNOakhJb2VuTnc9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzIzNTc0OTY2QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkU2NDFCNUJGNzk3MzlDMTc0NEFDM0ExMTlDRkQ0MEY0In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTMyNzM3NDF9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NDcyMzU3NDk2NkBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI2NUVEQUJGNjNDMTQ2NEE2N0ZGNDI4RUM5RTg4RkNGMiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzUzMjczNzQxfSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3MjM1NzQ5NjZAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQTYwODg4ODYxNjI5MTI0NDNGQTk3MjBFQUNFMUI1QUQifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1MzI3Mzc2NH1dLCJuZXh0UHJlS2V5SWQiOjYxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6NjEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiSk5SRU1TS0oiLCJtZSI6eyJpZCI6IjI1NDcyMzU3NDk2Njo0QHMud2hhdHNhcHAubmV0IiwibGlkIjoiMTAwMDI2MTQ3NzI5NjU2OjRAbGlkIiwibmFtZSI6ImpBeeKcjO+4jyJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTVgyNlpvREVQbXFnOFFHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiU1d5NmJsL3YwNm5qTUVyZXhkRUJ0MnJ4dGN4SC9QWGtPWDNOZk9JbUNVOD0iLCJhY2NvdW50U2lnbmF0dXJlIjoibTN2YTZEbEJKVGFGaTN0d01NdHFOd3h5UERJTlUzUExiUCtUY3pxazZWRmZOZ1FuTENMV0k1dmRQS05uRTVPbkh6N2VxOVJ3VWhDY2dPR3c4cUExQVE9PSIsImRldmljZVNpZ25hdHVyZSI6IkcvM3U5L2YyVkNMT3RrQjhXS1RrZ285L1NYSWs3U3gvY2x5L0JtMENudEIzVVYrWlByblcwUUJ3SnJaUTl6VjNiSURqemUzZno3YWtZenlKd2NUVGdnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0NzIzNTc0OTY2OjRAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCVWxzdW01Zjc5T3A0ekJLM3NYUkFiZHE4YlhNUi96MTVEbDl6WHppSmdsUCJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0JJSUJRPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzUzMjczNzM1LCJsYXN0UHJvcEhhc2giOiIzUjlaMzkiLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQVB4SiJ9';
const appname = process.env.APP_NAME || '';
const herokuapi = process.env.HEROKU_API;
const botname = process.env.BOTNAME || '𝗛𝗬𝗣𝗘𝗥-𝗕𝗢𝗧';
const author = process.env.STICKER_AUTHOR || '𝗕𝗢𝗧';
const packname = process.env.STICKER_PACKNAME || '𝗛𝗬𝗣𝗘𝗥';
const dev = process.env.DEV || '254794597254';
const owner = dev.split(",");
const menulink = process.env.MENU_LINK || 'https://files.catbox.moe/vev67n.jpg;
const menu = process.env.MENU_TYPE || 'VIDEO';
const bad = process.env.BAD_WORD || 'fuck';
const admin = process.env.ADMIN_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗿𝗲𝘀𝗲𝗿𝘃𝗲𝗱 𝗳𝗼𝗿 𝗔𝗱𝗺𝗶𝗻𝘀!';
const group = process.env.GROUP_ONLY_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝗚𝗿𝗼𝘂𝗽𝘀!';
const botAdmin = process.env.BOT_ADMIN_MSG || '𝗜 𝗻𝗲𝗲𝗱 𝗔𝗱𝗺𝗶𝗻 𝗽𝗿𝗲𝘃𝗶𝗹𝗲𝗱𝗴𝗲𝘀!';
const NotOwner = process.env.NOT_OWNER_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝘁𝗵𝗲 𝗼𝘄𝗻𝗲𝗿!';
const mycode = process.env.CODE || '254';
const port = process.env.PORT || 8080;
const databaseUrl = process.env.DATABASE_URL || '';

module.exports = {
  session,
  sessionName,
  author,
  packname,
  dev,
  owner,
  bad,
  group,
  NotOwner,
  botname,
  botAdmin, 
  menu,
  menulink,
  admin,
  mycode,
  herokuapi,
  port,
  appname,
  databaseUrl
};
  
