
// if you're using pannel carefully edit this part.

const sessionName = 'session';
const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkhhZ21QaVUxaG0vcDFUREdTZ2E3bG51UkJYUUZ5c0dJS2FVcnpOZDMyQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiem51RnRwSzFtTXJFVUJ1MG9FR2s2Rzd4dHZ3Zkc3Q0wwVTdsTk1LcGhXST0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJHRWdXWEJKMDIyS2JZY0JoS1NlM1ZjcVc1SjRkanY3N0VMTDFOdFFzYzJZPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJHTXVGRUc4RzdvYXBmZUZFM3FZbHJHNVpXVXZPT1RnSGlOMzJmeS84TFdNPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImtIQlVCd3ZqVG5EQWUwNUNrQ2xJTDlod3I1TFBuanBraEFjRGZwZGJqa0U9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IitONHJjbzErWkZCTHovSU4yWk1jMjFnNXdjOXdpRnFZdlg1Y3FzNkJXMkk9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT0ViUnAxNGlJcDNrUHNFeW96YTNDbzUxcGZ2azNrMlpYdEdHZmNMK1BIWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOXNXV2JzbVpmaEN0dEt1cGc5cnQzOWxjMGtXNHJUcldmQkNBNlJINGdHYz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlduRGV3NGtzNFVGTW8zbDJBV2VtUlNaRWY1Q1FMTCtxOUFHczd5djJ3UWRDakhpWWNvQVdvaXpKbndSVlppWDRwdjBkc3JmYytCMnlqQTEyY2FXNWlBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MzEsImFkdlNlY3JldEtleSI6Im1mWUNLSTVYVlp4MEJEcFhLN2ovT2pzZzZ6dGxreWhKSm5KVTl1bkJ0Wm89IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzIzNTc0OTY2QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjAwMkQ4RkVCOTVFNTIyQTUzQ0MyN0IwNkQ5NDE2MjM0In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTMyODg2Njh9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NDcyMzU3NDk2NkBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJGQTc0QTJEOTAyNUZFNzNFNzBBNDQwODQwRThDNDE2RiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzUzMjg4NjY4fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3MjM1NzQ5NjZAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiREU3MzJBNzUyQzI2MkFCOTQ5QTQwNjkwOTQwNTI2RkIifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1MzI4ODY3OH1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiQ1oxTFEyNDIiLCJtZSI6eyJpZCI6IjI1NDcyMzU3NDk2Njo1QHMud2hhdHNhcHAubmV0IiwibGlkIjoiMTAwMDI2MTQ3NzI5NjU2OjVAbGlkIiwibmFtZSI6ImpBeeKcjO+4jyJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTWIyNlpvREVNbWZoTVFHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiU1d5NmJsL3YwNm5qTUVyZXhkRUJ0MnJ4dGN4SC9QWGtPWDNOZk9JbUNVOD0iLCJhY2NvdW50U2lnbmF0dXJlIjoiaGJHNndMZ2JUb2NENXhiZHR3dUVoSUpkSmxsUXRhbCttWnFlS3lsczRJQzlqQWxRczNkYkc5WWx2Z0Qrbkt5WmZRMVRCYTlDbm9ycC9OaTJZSmNvQ3c9PSIsImRldmljZVNpZ25hdHVyZSI6IjVtRnB1R2Q5SG03N0xxMzduUmo3L09Zczc2MURaWmoxMCtqTFV6ckVJNnpIcW9aODJvREN5blZvTUVzTWNiMXl4V3ZScm1sL2xEMVJYK2x1dmpVMGd3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0NzIzNTc0OTY2OjVAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCVWxzdW01Zjc5T3A0ekJLM3NYUkFiZHE4YlhNUi96MTVEbDl6WHppSmdsUCJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0JJSUJRPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzUzMjg4NjYzLCJsYXN0UHJvcEhhc2giOiIzUjlaMzkiLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQVB4TCJ9';
const appname = process.env.APP_NAME || '';
const herokuapi = process.env.HEROKU_API;
const botname = process.env.BOTNAME || '𝗛𝗬𝗣𝗘𝗥-𝗕𝗢𝗧';
const author = process.env.STICKER_AUTHOR || '𝗕𝗢𝗧';
const packname = process.env.STICKER_PACKNAME || '𝗛𝗬𝗣𝗘𝗥';
const dev = process.env.DEV || '254794597254';
const owner = dev.split(",");
const menulink = process.env.MENU_LINK || 'https://files.catbox.moe/vev67n.jpg;
const menu = process.env.MENU_TYPE || 'VIDEO';
const bad = process.env.BAD_WORD || 'fuck';
const admin = process.env.ADMIN_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗿𝗲𝘀𝗲𝗿𝘃𝗲𝗱 𝗳𝗼𝗿 𝗔𝗱𝗺𝗶𝗻𝘀!';
const group = process.env.GROUP_ONLY_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝗚𝗿𝗼𝘂𝗽𝘀!';
const botAdmin = process.env.BOT_ADMIN_MSG || '𝗜 𝗻𝗲𝗲𝗱 𝗔𝗱𝗺𝗶𝗻 𝗽𝗿𝗲𝘃𝗶𝗹𝗲𝗱𝗴𝗲𝘀!';
const NotOwner = process.env.NOT_OWNER_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝘁𝗵𝗲 𝗼𝘄𝗻𝗲𝗿!';
const mycode = process.env.CODE || '254';
const port = process.env.PORT || 8080;
const databaseUrl = process.env.DATABASE_URL || '';

module.exports = {
  session,
  sessionName,
  author,
  packname,
  dev,
  owner,
  bad,
  group,
  NotOwner,
  botname,
  botAdmin, 
  menu,
  menulink,
  admin,
  mycode,
  herokuapi,
  port,
  appname,
  databaseUrl
};
  
